/*===========================================================================*
* Flow:         Flow1.flw
* ID:           
* Created:      2022-05-05T12:46:00.851145257Z
* Created by:   itarox
* Modified:     2022-05-05T12:46:00.851145257Z
* Modified by:  itarox
*
* Input Tables:
*   WORK.A
*
* Output Tables:
*   WORK.A
*
* Version:       DataFlows stable 2021.2.6 (20220425.1650860754033)
*
* Generated On:  2022-05-05T12:46:00.851145257Z
* Generated by:  itarox
*============================================================================*/
/* region: Generated preamble */

%studio_hide_wrapper;
/* Make sure the current directory is writable */
data _null_;
    length rc 4;
    %let tworkloc="%sysfunc(getoption(work))";
    rc=dlgcdir(&tworkloc);
run;

/* Setup options */
title;
footnote;
options validvarname=any;
options validmemname=extend;
options dtreset date number;
options device=png;

/* Setup macro variables */
%let syscc=0;
%let _clientapp = %nrquote(%nrstr(SAS Studio));
%let _clientappabbrev = %nrquote(%nrstr(Studio));
%let _clientappversion=2021.2.6;
%let _clientversion=6.727.36;
%let _sasservername=&SYSHOSTNAME;
%let _sashostname=&SYSHOSTNAME;
%let _sasprogramfilehost=&SYSHOSTNAME;
%let _clientuserid = %nrquote(%nrstr(itarox));
%let _clientusername = %nrquote(%nrstr(Rossella Axo));
%let clientmachine = %nrquote(%nrstr());
%let _clientmachine = %nrquote(%nrstr());
%let _clientmode = %nrquote(%nrstr(viya));
%let sasworklocation="%sysfunc(getoption(work))/";
filename _cwd &sasworklocation;
data _null_;
    call symput('_sasworkingdir',pathname('_cwd'));
run;
filename _cwd;
%let _sasprogramfile = %nrquote(%nrstr());
%let _baseurl = %nrquote(%nrstr(https://trcv009.trc.sas.com/SASStudio/));
%let _execenv = %nrquote(%nrstr(SASStudio;));
%symdel _dataout_mime_type _dataout_name _dataout_url _dataout_table / nowarn;
%let _sasws_ = %bquote(%sysfunc(getoption(work)));
%let _saswstemp_ = %bquote(%sysfunc(getoption(work)));

/* Detect SAS/Graph and setup graph options */
data _null_;
    length rc $255;
    call symput("graphinit","");
    call symput("graphterm","");
    rc=tslvl('sasxgopt','n');
    _error_=0;
    if (rc^=' ') then do;
        call symput("graphinit","goptions reset=all gsfname=_gsfname;");
        call symput("graphterm","goptions noaccessible;");
    end;
run;
data _null_;
    length rc 4;
    rc=sysprod("PRODNUM002");
    if (rc^=1) then do;
        call symput("graphinit","");
        call symput("graphterm","");
    end;
run;

/* Setup ODS destinations */
ods _all_ close;
filename _htmlout temp;
filename _listout temp;
filename _gsfname temp;
filename _dataout temp;
ods autonavigate off;
ods graphics on;
ods html5 (id=web) METATEXT='http-equiv="Content-Security-Policy" content="default-src ''none''; style-src ''unsafe-inline''; img-src data: ;"' device=png gpath="&_saswstemp_" path="&_saswstemp_" encoding=utf8 file=_htmlout (title='Results:Flow1.flw') style=Illuminate options(bitmap_mode='inline' outline='on' svg_mode='inline' css_prefix='.ods_940fbda3-56d2-4e21-8418-1ac47525a997' body_id='div_940fbda3-56d2-4e21-8418-1ac47525a997' );
ods listing file=_listout;
&graphinit;
%studio_restore_wrapper;

/* endregion */

/* region: Generated flow setup */
%macro _flw_action_start(nodes);
    data _null_;
        dtEndStr = put(datetime(), E8601DZ.);
        put "_FLW_ACTION_START_|" dtEndStr +(-1) "|&nodes";
    run;
%mend _flw_action_start;
%macro _flw_action_end(nodes, table_libs, libs, table_names);
    data _null_;

        attrib next_table_name length = $32 informat = $32. format = $32.
               dtStartStr length = $26 informat = $26. format = $26.;

        %local i next_table;
        %do i=1 %to %sysfunc(countc(&table_libs, |)) + 1;
            %let next_table = %qscan(&table_libs, &i, |);
            %let next_lib = %qscan(&libs, &i, |);
            %let next_table_name = %qscan(&table_names, &i, |);
            next_table_name = kreverse(ksubstr(kreverse(ksubstr(kstrip("&next_table_name."),2)),2));
            %let table_exists = %eval(%sysfunc(exist(&next_table, data)) or %sysfunc(exist(&next_table, view)));
            put "_FLW_ACTION_TABLE_|&next_lib|" next_table_name +(-1) "|&table_exists";
        %end;
        dtStartStr = put(datetime(), E8601DZ.);
        put "_FLW_ACTION_END_|" dtStartStr +(-1) "|&nodes";
    run;
%mend _flw_action_end;
/* endregion */

/*===========================================================================*
* Node name:        SAS Program
* Node ID:          id-1651746327770-1007
*
* Output Tables:
*   WORK.A
*
* Step name:        SAS Program
* Step URI:         /dataFlows/steps/a7190700-f59c-4a94-afe2-214ce639fcde
* Step description: Run user written SAS code.
*----------------------------------------------------------------------------*/

/* region: Generated step setup */
%_flw_action_start(id-1651746327770-1007);
/* endregion */


/* region: Generated macro initialization */
%let _inputCount = 0;
%let _outputCount = 1;
%let _output1 = WORK.A;

/* endregion */

data b ; set sashelp.class; run;

/* region: Generated macro cleanup */
%symdel _inputCount;
%symdel _outputCount;
%symdel _output1;

/* endregion */


/* region: Generated step cleanup */
%_flw_action_end(id-1651746327770-1007, WORK.A, WORK, "A");
/* endregion */

/* region: Generated flow cleanup */
%sysmacdelete _flw_action_start;
%sysmacdelete _flw_action_end;
/* endregion */
/* region: Generated postamble */

%studio_hide_wrapper;
/* Close ODS destinations */
&graphterm; ;*';*";*/;run;quit;
quit;run;
ods html5 (id=web) close;
ods listing close;
%if %sysfunc(fileref(_gsfname)) lt 0 %then %do;
    filename _gsfname clear;
%end;
%studio_restore_wrapper;

/* endregion */


